### ISSUE TITLE
Nextjs duckdb connection

### ISSUE THREAD

**Issue by selimsezr** [motherduckdb/duckdb-async#35]
Hi everyone I'm developing apps with nextjs but I have a connection problem. How can i solve this issue?

```
//api/dbCheck
import { Connection, Database } from "duckdb-async";
import path from "path";

export async function GET() {
     const dbPath = path.join(process.cwd(), "duckdb.db");
      console.log(dbPath);  
      async function simpleTest() {
   
      const db = await Database.create(dbPath);
     
      console.log(db.connect());
      }
      
      simpleTest();
  return Response.json({ message: "Hello, Next.js!" });
}
```

```
⨯ ./node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:1
Module not found: Can't resolve 'mock-aws-s3'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/duckdb/lib/duckdb-binding.js
./node_modules/duckdb/lib/duckdb.js
./node_modules/duckdb-async/dist/duckdb-async.js
./src/app/api/dbCheck/route.ts
 GET /api/dbCheck 500 in 34ms
```

**Comment by jdbohrman** [comment]
Also an issue here and it seems tons of others are experiencing it

**Comment by antonycourtney** [comment]
[ Reponse here also shared on DuckDb Discord in the `nodejs` channel]:
The issue with getting DuckDb working on Next.JS is really a downstream package issue (see this github issue: https://github.com/mapbox/node-pre-gyp/issues/661#issuecomment-1347186316 ). The raw duckdb nodeJS bindings have the same issue as far as I know, it really doesn't have anything to do with the use of duckdb-async, which is really just thin promise wrappers around the underlying Node.JS package.  See this article and associated package from @TobiLG  for what's involved in getting DuckDb working on AWS Lambda (though I'm not sure if this works for NextJS): https://tobilg.com/using-duckdb-in-aws-lambda

I am going to close this issue since it's really not a `duckdb-async` specific issue as far as I can see.

**Comment by selimsezr** [comment]
I tried with this library but does not work. This problem like bcryptjs  problem but there are AWS libraries at duckDB. I connected with using expressJS

**Comment by tobilg** [comment]
> I tried with this library but does not work. This problem like bcryptjs problem but there are AWS libraries at duckDB. I connected with using expressJS

I‘m pretty confident it works if you use https://www.npmjs.com/package/duckdb-lambda-x86 instead of the normal duckdb package…

**Comment by rafaeldcf** [comment]
I got this working by adding the following to my **next.config.ts** file:
`serverExternalPackages: ["@duckdb"]`
