### ISSUE TITLE
Tagged Releases

### ISSUE THREAD

**Issue by tnightengale** [motherduckdb/duckdb-async#4]
Out of curiosity, is there a reason this repository is not tagging the releases that are [present on npmjs](https://www.npmjs.com/package/duckdb-async?activeTab=versions)?

**Comment by antonycourtney** [comment]
@tnightengale There is no deep reason for the lack of tags, just an artifact of me tracking the corresponding duckdb version and just publishing the package manually with `npm publish`.
Do you have a preferred / recommended workflow here?  Would it be helpful for me to always manually do a `git tag` with the corresponding version before publishing?
Also happy to just explicitly tag the latest as `v7.0.1` right now, and try and always do this before publish going forward if you would find that helpful.
 
Longer term we will work with the DuckDb Labs team to move this package into the main duckdb repository so that it's always published along with every duckdb release.

**Comment by antonycourtney** [comment]
...pushed a missing commit 😳 and added a tag for `v0.7.1`. Closing.

**Comment by tnightengale** [comment]
@antonycourtney Thank you! I ask because I saw a `git clone` workflow in [an issue of you opened](https://github.com/duckdb/duckdb/issues/5605) in the main duckdb repository. I was wondering the reason behind that approach vs `npm install` and then noticed the point was moot because of lack of tags here.

I appreciate the tag for 0.7.1, and I don't think it's worth the effort to add a Github Actions pipeline if you plan to merge this into the main duckdb repository soon.

Cheers!
