### ISSUE TITLE
Large memory usage over Python equivalent

### ISSUE THREAD

**Issue by vimota** [motherduckdb/duckdb-async#5]
Hi :) I'm running into [memory issues that lead my server to OOM](https://github.com/duckdb/duckdb/issues/6607) and while trying to isolate that I found that Nodejs / duckdb-async uses much more memory than the equivalent Python API:

[Nodejs + duckdb-async](https://gist.github.com/vimota/67c145c1ce0bdec756a289c1f38cb4ed) - peaks at around 3.7GB on my M1 Pro 16GB ram
[Python + duckdb](https://gist.github.com/vimota/1735ed29bcce83695f170192501bac75) - peaks at around 2.6GB on my M1 Pro 16GB ram

I'm not totally sure if it's the duckdb-async layer or the nodejs binding but posting here in case you have any thoughts!

**Comment by vimota** [comment]
Actually, it doesn't seem to be due to this library (duckdb-async) but something about to do with the nodejs bindings, I've repro'd it with just the native node bindings and I'm seeing the same thing: https://gist.github.com/vimota/23f40bca01593a3731c37779dc00cb9c

**Comment by antonycourtney** [comment]
Hi @vimota -- Thanks for taking the time to check that it's not the duckdb-async bindings causing the issue, but the underlying duckdb node bindings.
I'd suggest opening in issue over in the main [duckdb repo](https://github.com/duckdb/duckdb) since that's where the node.js bindings are maintained.  Having a repro like your gist is good, but of course the smaller you can make it, the better.  I'd also suggest checking the baseline mem usage and what the memory growth looks like when running queries; node.js (and its underlying V8 engine) taking more memory than Python isn't too surprising on its own.

Closing this issue for now. Good luck!
